# Generated by Django 3.2.19 on 2023-07-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalartwork',
            name='carousel',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalartwork',
            name='image_alt',
            field=models.CharField(default='alt text', max_length=254),
            preserve_default=False,
        ),
    ]
