# Generated by Django 3.2.19 on 2023-07-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_artworks', '0002_auto_20230706_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalartwork',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
