# Generated by Django 3.2.19 on 2023-07-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_artworks', '0003_alter_digitalartwork_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalartwork',
            name='daw_url',
        ),
    ]
