# Generated by Django 3.2.19 on 2023-07-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_artworks', '0004_remove_digitalartwork_daw_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalartwork',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='digitalartwork',
            name='size',
        ),
    ]
