# Generated by Django 3.2.19 on 2023-07-08 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='variation',
            field=models.CharField(blank=True, max_length=245, null=True),
        ),
    ]
