# Generated by Django 3.2.19 on 2023-07-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_digital_artwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
